include: package:lint/analysis_options_package.yaml


analyzer:
  exclude:
    - example/**

  errors:
    sort_unnamed_constructors_first: ignore
    avoid_redundant_argument_values: ignore
    constant_identifier_names: ignore
    avoid_positional_boolean_parameters: ignore
    prefer_initializing_formals: ignore
    
    